// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAaGIohQT0kieF2CLMcV_w5GjAAKnBad7I',
    appId: '1:676775287106:web:f7096eb62a0784b4bfd0db',
    messagingSenderId: '676775287106',
    projectId: 'aegischeck',
    authDomain: 'aegischeck.firebaseapp.com',
    storageBucket: 'aegischeck.firebasestorage.app',
    measurementId: 'G-P70EL79W84',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDoYX7FAG-Q-SKcA5SYxLB6_gMi6R23Doo',
    appId: '1:676775287106:android:6d4c74915091938dbfd0db',
    messagingSenderId: '676775287106',
    projectId: 'aegischeck',
    storageBucket: 'aegischeck.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCu0cY-Vl3VJqkfkwTadTJeW4IPBHS3HX8',
    appId: '1:676775287106:ios:be2c095d02bbb570bfd0db',
    messagingSenderId: '676775287106',
    projectId: 'aegischeck',
    storageBucket: 'aegischeck.firebasestorage.app',
    iosBundleId: 'com.aegischeck.aegischeck',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAaGIohQT0kieF2CLMcV_w5GjAAKnBad7I',
    appId: '1:676775287106:web:9ca5f1ba7c23fc90bfd0db',
    messagingSenderId: '676775287106',
    projectId: 'aegischeck',
    authDomain: 'aegischeck.firebaseapp.com',
    storageBucket: 'aegischeck.firebasestorage.app',
    measurementId: 'G-WV9CG6DQ9C',
  );
}
